application: vestigoapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /pages
  static_dir: pages

- url: /
  static_files: pages/index.html
  upload: pages/index.html

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /.*
  script: vestigoapp.py
  login: required

error_handlers:
- file: /pages/error_default.html

- error_code: over_quota
  file: /pages/error_quota.html